# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatchain < Formula
  desc "A lightweight cross-platform AI chat CLI"
  homepage "https://github.com/joyqi/chatchain"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joyqi/chatchain/releases/download/v1.0.1/chatchain_1.0.1_darwin_amd64.tar.gz"
      sha256 "badc737507485abbf81880096ac8e1c35e8077d92d5f3a0878f0d3eaea330a76"

      define_method(:install) do
        bin.install "chatchain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joyqi/chatchain/releases/download/v1.0.1/chatchain_1.0.1_darwin_arm64.tar.gz"
      sha256 "70b522a328d39d90ea37c88a6654e027e986169f89026f5c10f8d5b28b769e30"

      define_method(:install) do
        bin.install "chatchain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joyqi/chatchain/releases/download/v1.0.1/chatchain_1.0.1_linux_amd64.tar.gz"
      sha256 "b2593d87e2078a3e204a40109699076d423e527d952241b641645a85f5d9f7c6"
      define_method(:install) do
        bin.install "chatchain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joyqi/chatchain/releases/download/v1.0.1/chatchain_1.0.1_linux_arm64.tar.gz"
      sha256 "4540a64384c151c840409dedfa1ce31fc15a41a1fc03e6c8f7446579a0fa721e"
      define_method(:install) do
        bin.install "chatchain"
      end
    end
  end
end
