# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatchain < Formula
  desc "A lightweight cross-platform AI chat CLI"
  homepage "https://github.com/joyqi/chatchain"
  version "2.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joyqi/chatchain/releases/download/v2.7.0/chatchain_2.7.0_darwin_amd64.tar.gz"
      sha256 "7db691ca9a6b235b3622a698218e92859a72c409b054470518b078cbabda3ade"

      define_method(:install) do
        bin.install "chatchain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joyqi/chatchain/releases/download/v2.7.0/chatchain_2.7.0_darwin_arm64.tar.gz"
      sha256 "c1ded173a6e4be00f9b5eb7678fd839b64e80ddb1d80bd5db7506329cc4db243"

      define_method(:install) do
        bin.install "chatchain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joyqi/chatchain/releases/download/v2.7.0/chatchain_2.7.0_linux_amd64.tar.gz"
      sha256 "03a796040ea52822c5dbf76ff864dc01602ffbfa57d1d8fa439c698230203024"
      define_method(:install) do
        bin.install "chatchain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joyqi/chatchain/releases/download/v2.7.0/chatchain_2.7.0_linux_arm64.tar.gz"
      sha256 "f194f76ba416046d29f7f09b80565b0ef5e3209893f5862744e3eefc3a10d93c"
      define_method(:install) do
        bin.install "chatchain"
      end
    end
  end
end
