# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatchain < Formula
  desc "A lightweight cross-platform AI chat CLI"
  homepage "https://github.com/joyqi/chatchain"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joyqi/chatchain/releases/download/v2.4.0/chatchain_2.4.0_darwin_amd64.tar.gz"
      sha256 "4577c3a000d6c2ddf7639c413509756978ae5a135a9efe4fe23ebd965e76c9e3"

      define_method(:install) do
        bin.install "chatchain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joyqi/chatchain/releases/download/v2.4.0/chatchain_2.4.0_darwin_arm64.tar.gz"
      sha256 "79b3b6ceb537a78f69f55eaf5d71502a1e89159e29cf31e7b3f6a89e48d9ec50"

      define_method(:install) do
        bin.install "chatchain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joyqi/chatchain/releases/download/v2.4.0/chatchain_2.4.0_linux_amd64.tar.gz"
      sha256 "29a373f436e3306c5d0c150e3b0ac6960335e125bb00e42f2debd529bafd37a8"
      define_method(:install) do
        bin.install "chatchain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joyqi/chatchain/releases/download/v2.4.0/chatchain_2.4.0_linux_arm64.tar.gz"
      sha256 "eb542283966c6f430a3b08198fc91d5d11bb9b131d91436ad16ac5d8c5ca983d"
      define_method(:install) do
        bin.install "chatchain"
      end
    end
  end
end
